# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('AT', 'Alta'), ('NR', 'Normal'), ('BJ', 'Baja')], max_length=7)),
                ('fecha_creacion_g', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
